### ISSUE TITLE
Request for naming convention for Jupyter notebooks

### ISSUE THREAD

**Issue by Mostafa-Atallah2020** [Innanov/Xanadu-Codebook-Solutions#1]
Hello team,

I noticed that the naming of the Jupyter notebooks in our repository is inconsistent, and this is becoming a challenge for us to keep track of all the notebooks and their contents. To resolve this issue, I would like to propose that we adopt a consistent naming convention for all the Jupyter notebooks.

Please share your thoughts and feedback on this proposal, and let's work together to implement a naming convention that works for everyone.

Thanks!

**Comment by Innanov** [comment]
yeah I agree, I think Node A... looks good, do you have any suggestions ?

**Comment by Mostafa-Atallah2020** [comment]
I suggest `Node X:**headline**.ipynb` as a naming convention.

Also, create a folder `./Nodes` containing all the notebooks.

**Comment by Innanov** [comment]
Perfect!
